from tkinter import *
from tkinter import messagebox
win=Tk()
x=win.winfo_screenwidth()
y=win.winfo_screenheight()
win.geometry(f'800x600+{(x-800)//2}+{(y-600)//2}')
#functions
def submit():
    if ent_name.get() != "" and ent_l_name.get() and g != "0":
        win_2=Toplevel(win)
        win_2.geometry(f'400x400+{(x - 400) // 2}+{(y - 400) // 2}')
        win_2.title("خوش آمدید")
        lbl_welcome=Label(win_2,text=f"{ent_l_name.get()} {ent_name.get()} {g.get()}خوش آمدید")
        lbl_welcome.pack(pady=10)
    else:
        messagebox.showerror("Error","اطلاعات کافی نمی باشد")
def exit():
    result=messagebox.askquestion("Exit","آیا می خواهید خارج شوید ")
    if result == "yes":
        win.destroy()
def clear():
    global ent_name,ent_l_name,ent_t,ent_n,i_python,i_network,i_c,i_linux,g
    ent_name.delete(0, END)
    ent_l_name.delete(0, END)
    ent_t.delete(0, END)
    ent_n.delete(0, END)
    i_python.set(0)
    i_network.set(0)
    i_c.set(0)
    i_linux.set(0)
    g.set("0")

#widgets
lbl_fr_1=LabelFrame(win,text="مشخصات فردی",labelanchor="ne")
lbl_fr_1.pack(pady=20,padx=10,fill="both")
frame_right_1=Frame(lbl_fr_1)
frame_right_1.pack(side="right",fill="both")
lbl_name=Label(frame_right_1,text=": نام")
lbl_name.pack(pady=10,padx=10,anchor="ne")
lbl_l_name=Label(frame_right_1,text=": نام خانوداگی")
lbl_l_name.pack(pady=10,padx=10,anchor="se")
frame_right_2=Frame(lbl_fr_1)
frame_right_2.pack(side="right",fill="both")
ent_name=Entry(frame_right_2,width=15)
ent_name.pack(pady=10,padx=10,anchor="ne")
ent_l_name=Entry(frame_right_2,width=15)
ent_l_name.pack(pady=10,padx=10,anchor="se")
frame_left_1=Frame(lbl_fr_1)
frame_left_1.pack(side="left",fill="both")
ent_t=Entry(frame_left_1,width=15)
ent_t.pack(pady=10,padx=10,anchor="nw")
ent_n=Entry(frame_left_1,width=15)
ent_n.pack(pady=10,padx=10,anchor="sw")
frame_left_2=Frame(lbl_fr_1)
frame_left_2.pack(side="left",fill="both")
lbl_name=Label(frame_left_2,text=": تحصیلات")
lbl_name.pack(pady=10,padx=10,anchor="nw")
lbl_l_name=Label(frame_left_2,text=": شماره")
lbl_l_name.pack(pady=10,padx=10,anchor="sw")
lbl_fr_2=LabelFrame(win,text="مهارت ها",labelanchor="ne")
lbl_fr_2.pack(pady=20,padx=10,fill="both")
i_python=IntVar()
i_network=IntVar()
i_c=IntVar()
i_linux=IntVar()
cek_p=Checkbutton(lbl_fr_2,text="Python",variable=i_python)
cek_p.pack(side="left",pady=10,padx=10)
cek_n=Checkbutton(lbl_fr_2,text="Network",variable=i_network)
cek_n.pack(side="left",pady=10,padx=10)
cek_c=Checkbutton(lbl_fr_2,text="C#",variable=i_c)
cek_c.pack(side="left",pady=10,padx=10)
cek_l=Checkbutton(lbl_fr_2,text="Linux",variable=i_linux)
cek_l.pack(side="left",pady=10,padx=10)
lbl_fr_3=LabelFrame(win,text="جنسیت",labelanchor="ne")
lbl_fr_3.pack(pady=20,padx=10,fill="both")
g=StringVar()
g.set("0")
rbn_1=Radiobutton(lbl_fr_3,text="مرد",variable=g,value="آقای ")
rbn_1.pack(anchor="ne",pady=10,padx=10)
rbn_2=Radiobutton(lbl_fr_3,text="زن",variable=g,value="خانم ")
rbn_2.pack(anchor="ne",pady=10,padx=10)
fr_4=Frame(win)
fr_4.pack(pady=20,padx=10,fill="both")
btn_sub=Button(fr_4,text="Submit",width=15,command=submit)
btn_sub.pack(side="left",pady=10,padx=10)
btn_clear=Button(fr_4,text="Clear",width=15,command=clear)
btn_clear.pack(side="left",pady=10,padx=10)
btn_exit=Button(fr_4,text="Exit",width=15,command=exit)
btn_exit.pack(side="left",pady=10,padx=10)
win.mainloop()